### PR TITLE
Fix well-formedness assumptions

### LINKED ISSUE #304: Investigate why struct test is failing in WF check
PR #282 left an odd error in `src/test/borrowck.rs`. See the conversation here:

https://github.com/rust-lang/a-mir-formality/pull/282#discussion_r3019048262

### PR DESCRIPTION
**Pull request by xonx4l**
## What does this PR do?
This PR  fix well-formedness assumptions and  address issue https://github.com/rust-lang/a-mir-formality/issues/304

Closes #304

## Disclosure and PR context

**AI tools used:** Yes , For research .

**Confidence level:** initial draft I need to work more on some specifics  

**Review depth:** I reviewed closely and understand it well

**Testing:** cargo test , cargo fmt check

**Questions for mentors:** None

### CODE REVIEW

File: crates/formality-rust/src/prove/prove/prove/prove_wf.rs [hunk 1]
```diff
@@ -31,6 +31,19 @@ judgment_fn! {
...
         )
 
+        (
+            // Use prove_wc so earlier assumptions still apply the well-formed rule skips these
+            // variables there so we do not loop forever.
+            (prove_wc(
+                decls,
+                env,
+                assumptions,
+                Upcast::<Parameter>::upcast(v.clone()).well_formed(),
```
Comment (nikomatsakis) [inline crates/formality-rust/src/prove/prove/prove/prove_wf.rs]:
```suggestion
                Relation::well_formed(v),
```

we should probably remove the `well_formed` method.

(If this doesn't work, we may need a 'transitive upcast impl' from `Relation` to `Wc` or `Wcs`, but I think one exists.)

Comment (nikomatsakis) [reply crates/formality-rust/src/prove/prove/prove/prove_wf.rs]: Wait. Hmm. This is not the fix I expected.

Comment (nikomatsakis) [reply crates/formality-rust/src/prove/prove/prove/prove_wf.rs]: I was expecting to modify this code...

https://github.com/rust-lang/a-mir-formality/blob/6a4d031757ad6da6931d6f43d2a41b9efa384c9d/crates/formality-rust/src/check/borrow_check/nll.rs#L279-L286

...to add an assumption `Relation::WellFormed(l)` for each `l` in `substs` -- i.e., each newly introduced variable.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Can you try the alternative approach I suggested?

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/a-mir-formality/309/6a4d031757ad6da6931d6f43d2a41b9efa384c9d..8d5b362cfec0c237678508cd6a9ccd37c40a19b3)*

File: crates/formality-rust/src/prove/prove/prove/prove_wf.rs (hunk 1 above)
Comment (xonx4l) [reply crates/formality-rust/src/prove/prove/prove/prove_wf.rs]: This clears a lot I had the same intent in mind WF for each fresh variable from `instantiate_existentially` on the exists path and routing the existential case through `prove_wc` so those assumptions apply but I did it with Parameter and  .well_formed() instead of `Relation::WellFormed` as that was the existing pattern in a few places . I’ll switch to `Relation::WellFormed` . Thanks for Guidance.

File: crates/formality-rust/src/check/borrow_check/nll.rs [hunk 2]
```diff
@@ -17,6 +18,17 @@ use formality_core::{judgment_fn, term, ProvenSet, Set, Union, Upcast};
 
 use crate::check::borrow_check::liveness::{Assignment, Either, LiveBefore, LivePlaces};
 
+// Treats each name brought in by exists as OK to use when checking the code inside.
+fn wf_assumptions_for_existential_subst(subst: &[ExistentialVar]) -> Wcs {
+    subst
+        .iter()
+        .map(|v| {
+            let p: Parameter = v.clone().upcast();
+            Upcast::<Wc>::upcast(p.well_formed())
```
Comment (nikomatsakis) [inline crates/formality-rust/src/check/borrow_check/nll.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/a-mir-formality/309/1ef507bd9787433d213f3505705166ce987e7593..698e85c3860d037acf04242dfd2b97f642542e50)*

I think this can `Relation::well_formed(p)` -- does that work? Ah, perhaps not quite, but we can change this code

https://github.com/rust-lang/a-mir-formality/blob/1ef507bd9787433d213f3505705166ce987e7593/crates/formality-rust/src/grammar/wc.rs#L82-L88

to be 

```rust
impl<T> FromIterator<T> for Wcs
where
    T: Upcast<Wc>,
{
    fn from_iter<T: IntoIterator<Item = Wc>>(iter: T) -> Self {
        Wcs {
            set: iter.into_iter().upcasted().collect(), // may have to import the `Upcased` trait
        }
    }
}
```

and then it should work.

Comment (nikomatsakis) [reply crates/formality-rust/src/check/borrow_check/nll.rs]: If that causes issues we could add a `.upcast)` but I'd prefer to modify the `FromIterator` impl.

File: crates/formality-rust/src/prove/prove/prove/prove_wc.rs [hunk 3]
```diff
@@ -158,6 +162,7 @@ judgment_fn! {
 
 
         (
+            (if !parameter_is_existential_variable(&p))!
```
Comment (nikomatsakis) [inline crates/formality-rust/src/prove/prove/prove/prove_wc.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/a-mir-formality/309/1ef507bd9787433d213f3505705166ce987e7593..698e85c3860d037acf04242dfd2b97f642542e50)*

Do we need this? It doesn't hurt I guess, but I'm not sure if we need it.

File: crates/formality-rust/src/prove/prove/prove/prove_wf.rs [hunk 4]
```diff
@@ -31,6 +31,19 @@ judgment_fn! {
...
+            ) => c)
+            --- ("existential variables")
+            (prove_wf(decls, env, assumptions, Variable::ExistentialVar(v)) => c)
```
Comment (nikomatsakis) [inline crates/formality-rust/src/prove/prove/prove/prove_wf.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/a-mir-formality/309/1ef507bd9787433d213f3505705166ce987e7593..698e85c3860d037acf04242dfd2b97f642542e50)*

If we are adding things in the environment then I think we can remove this rule.

File: src/test/borrowck.rs [hunk 5]
```diff
@@ -1767,3 +1770,131 @@ fn call_mut_under_shared_borrow() {
...
+
+            the rule "write-indirect" at (nll.rs) failed because
+              pattern `TypedPlaceExpressionData::Deref(place_loaned_ref)` did not match value `p : Point . x`"#]]
+    )
+}
+
+// Constructing a struct that reads a local variable that is mutably borrowed — borrow error.
+#[test]
+fn struct_construction_with_borrowed_local() {
+    crate::assert_err!(
```
Comment (nikomatsakis) [inline src/test/borrowck.rs:1843]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/a-mir-formality/309/1ef507bd9787433d213f3505705166ce987e7593..698e85c3860d037acf04242dfd2b97f642542e50)*

Wait, how did these tests get in this PR? Is this a rebase artifact...? Or intentional.

Comment (pranavpurankar) [reply src/test/borrowck.rs:1843]: @nikomatsakis I think, I can clear up the confusion on zulip, [discussion link](https://rust-lang.zulipchat.com/#narrow/channel/402470-t-types.2Fformality/topic/.5BGFI.5D.20Expand.20test.20coverage.20for.20Expr.20variants.20formality.23265/near/584287907)

Comment (xonx4l) [reply src/test/borrowck.rs:1843]: Yes this is a rebase artifact not intentional.

File: crates/formality-rust/src/prove/prove/prove/prove_wc.rs (hunk 3 above)
Comment (xonx4l) [reply crates/formality-rust/src/prove/prove/prove/prove_wc.rs]: Yes this becomes  redundant after removing the existential prove_wf rule.

**Comment by xonx4l** [comment]
going to fix the CI failures .

File: crates/formality-rust/src/grammar/wc.rs [hunk 6]
```diff
@@ -79,10 +79,13 @@ impl IntoIterator for Wcs {
     }
 }
 
-impl FromIterator<Wc> for Wcs {
-    fn from_iter<T: IntoIterator<Item = Wc>>(iter: T) -> Self {
+impl<I> FromIterator<I> for Wcs
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/wc.rs:82]: Ah, *this* is what caused the other fallout?

File: crates/formality-rust/src/prove/prove/prove/prove_eq.rs [hunk 7]
```diff
@@ -220,7 +220,7 @@ fn equate_variable(
         .iter()
         .filter(|(v, _)| v.is_a::<UniversalVar>())
         .map(|(v, p)| eq(v, p))
-        .upcasted()
+        .map(|r| Upcast::<Wc>::upcast(r))
```
Comment (nikomatsakis) [inline crates/formality-rust/src/prove/prove/prove/prove_eq.rs:223]:
```suggestion
```

File: crates/formality-rust/src/grammar/wc.rs [hunk 8]
```diff
@@ -49,7 +49,7 @@ impl Wcs {
         let b: Parameter = b.upcast();
         a.into_iter()
             .map(|a| Relation::outlives(a, &b))
-            .upcasted()
+            .map(|r| Upcast::<Wc>::upcast(r))
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/wc.rs:52]:
```suggestion
```

File: crates/formality-rust/src/grammar/wc.rs [hunk 9]
```diff
@@ -39,7 +39,7 @@ impl Wcs {
         a.into_iter()
             .zip(b)
             .map(|(a, b)| Relation::sub(a, b))
-            .upcasted()
+            .map(|r| Upcast::<Wc>::upcast(r))
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/wc.rs:42]:
```suggestion
```

File: crates/formality-rust/src/grammar/wc.rs [hunk 10]
```diff
@@ -25,7 +25,7 @@ impl Wcs {
         a.into_iter()
             .zip(b)
             .map(|(a, b)| Relation::equals(a, b))
-            .upcasted()
+            .map(|r| Upcast::<Wc>::upcast(r))
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/wc.rs:28]:
```suggestion
```

File: crates/formality-rust/src/grammar/traits_and_impls.rs [hunk 11]
```diff
@@ -189,8 +186,8 @@ impl WhereClause {
                 let ct_param: Parameter = ct.upcast();
                 let ty_param: Parameter = ty.upcast();
                 [
-                    ct_param.well_formed().upcast(),
-                    ty_param.well_formed().upcast(),
+                    Upcast::<Wc>::upcast(ct_param.well_formed()),
+                    Upcast::<Wc>::upcast(ty_param.well_formed()),
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/traits_and_impls.rs:190]:
```suggestion
                    ct_param.well_formed(),
                    ty_param.well_formed(),
```

File: crates/formality-rust/src/grammar/traits_and_impls.rs [hunk 12]
```diff
@@ -172,8 +169,8 @@ impl WhereClause {
                 let a_param: Parameter = a.upcast();
                 let b_param: Parameter = b.upcast();
                 [
-                    a_param.well_formed().upcast(),
-                    b_param.well_formed().upcast(),
+                    Upcast::<Wc>::upcast(a_param.well_formed()),
+                    Upcast::<Wc>::upcast(b_param.well_formed()),
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/traits_and_impls.rs:173]:
```suggestion
                    a_param.well_formed(),
                    b_param.well_formed(),
```

File: crates/formality-rust/src/grammar/traits_and_impls.rs [hunk 13]
```diff
@@ -156,14 +153,14 @@ impl WhereClause {
...
+                Upcast::<Wcs>::upcast(trait_id.with(self_ty, parameters).well_formed())
             }
             WhereClauseData::AliasEq(alias_ty, ty) => {
                 let alias_param: Parameter = alias_ty.upcast();
                 let ty_param: Parameter = ty.upcast();
                 [
-                    alias_param.well_formed().upcast(),
-                    ty_param.well_formed().upcast(),
+                    Upcast::<Wc>::upcast(alias_param.well_formed()),
+                    Upcast::<Wc>::upcast(ty_param.well_formed()),
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/traits_and_impls.rs:163]:
```suggestion
                    alias_param.well_formed(),
                    ty_param.well_formed(),
```

File: crates/formality-rust/src/grammar/traits_and_impls.rs [hunk 14]
```diff
@@ -156,14 +153,14 @@ impl WhereClause {
     pub fn well_formed(&self) -> Wcs {
         match self.data() {
             WhereClauseData::IsImplemented(self_ty, trait_id, parameters) => {
-                trait_id.with(self_ty, parameters).well_formed().upcast()
+                Upcast::<Wcs>::upcast(trait_id.with(self_ty, parameters).well_formed())
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/traits_and_impls.rs:156]:
```suggestion
                trait_id.with(self_ty, parameters).well_formed()
```

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Ugh, I had this pending review and I never submitted it. I'm sorry @xonx4l 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/a-mir-formality/309/288f923ceac3e1c6e3eb382a01f8a2c2c29e5168..9b684a80c5fcdea583d1911dc0ef7eb4b4f967cd)*

**Comment by nikomatsakis** [comment]
Let me know if those simplifications *don't* work

File: crates/formality-rust/src/grammar/traits_and_impls.rs [hunk 15]
```diff
@@ -137,10 +137,7 @@ impl WhereClause {
     pub fn invert(&self) -> Option<Wc> {
         match self.data() {
             WhereClauseData::IsImplemented(self_ty, trait_id, parameters) => Some(
-                trait_id
-                    .with(self_ty, parameters)
-                    .not_implemented()
-                    .upcast(),
+                Upcast::<Wc>::upcast(trait_id.with(self_ty, parameters).not_implemented()),
             ),
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/traits_and_impls.rs:141]:
```suggestion
            ).upcast(),
```

File: crates/formality-rust/src/grammar/traits_and_impls.rs [hunk 16]
```diff
@@ -137,10 +137,7 @@ impl WhereClause {
     pub fn invert(&self) -> Option<Wc> {
         match self.data() {
             WhereClauseData::IsImplemented(self_ty, trait_id, parameters) => Some(
-                trait_id
-                    .with(self_ty, parameters)
-                    .not_implemented()
-                    .upcast(),
+                Upcast::<Wc>::upcast(trait_id.with(self_ty, parameters).not_implemented()),
```
Comment (nikomatsakis) [inline crates/formality-rust/src/grammar/traits_and_impls.rs:140]:
```suggestion
                trait_id.with(self_ty, parameters).not_implemented()
```

**Review by nikomatsakis — APPROVED** [review]
Ok, I don't like the `Upcast` calls but I'm just going to merge this PR  at this point so we can fix them later

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/a-mir-formality/309/8403198f79de7bf8be3381b5837c29823675fe15..9beb4f695d7e20b87fc8accb527aee32038cd4ac)*
